# Site settings
title: Web-Framework
email: info@lazercube.com

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
port: 80

exclude: ["node_modules", "gulpfile.js", "package.json"]
